### ISSUE TITLE
What might have happened to the dark red color of all the pictures that came out of the deep estimate?

### ISSUE THREAD

**Issue by gnulife** [apple/ml-depth-pro#12]
![91_2](https://github.com/user-attachments/assets/77e0088a-f026-45af-9e57-bb954815c12e)
What might have happened to the dark red color of all the pictures that came out of the deep estimate?

**Comment by Amael** [comment]
Could be wrong visualization? Try again with [this change](https://github.com/apple/ml-depth-pro/commit/b2cd0d51daa95e49277a9f642f7fd736b7f9e91d) or provide more info.
