### ISSUE TITLE
Depth for right half of image incorrect

### ISSUE THREAD

**Issue by 99991** [apple/ml-depth-pro#19]
The user [zimperfish on HackerNews](https://news.ycombinator.com/item?id=41748360) noticed that the depth for [this image](https://imgur.com/a/garden-depth-pro-test-nFYtl77) is incorrect. Scaling the range of the depth map to a more visible range reveals that the right half of the depth map is different from the left half. Downscaling the image to 768x1024 or 384x512 does not help.

I have not yet looked into why this happens, but if it is caused by an outlier in the feature maps, it may be possible to fix it by clipping.

# Code to reproduce

```python
from PIL import Image
import numpy as np
import depth_pro
import torch
import requests

def download_file(url, filename):
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"}

    with requests.get(url, headers=headers) as r:
        r.raise_for_status()
        data = r.content

    with open(filename, "wb") as f:
        f.write(data)

url = "https://i.imgur.com/2M4rhac.jpeg"
image_path = "data/2M4rhac.jpeg"

download_file(url, image_path)

# Load model and preprocessing transform
model, transform = depth_pro.create_model_and_transforms()
model.eval()

# Load and preprocess an image.
image, _, f_px = depth_pro.load_rgb(image_path)
image = transform(image)

# Run inference.
prediction = model.infer(image, f_px=f_px)
depth = prediction["depth"]  # Depth in [m].
focallength_px = prediction["focallength_px"]  # Focal length in pixels.

depth = depth.detach().cpu().numpy()

# Normalize image to [5 %, 95 %] range
s = np.sort(depth)
n = len(s)
a = s[int(0.05 * n)]
b = s[int(0.95 * n)]
depth = (depth - a) / (b - a)

Image.fromarray(np.clip(depth * 255, 0, 255).astype(np.uint8)).save("depth.png")
```

# Resulting depth map

![depth](https://github.com/user-attachments/assets/482adadb-ca04-43da-a619-c68cde3faa2d)

**Comment by Amael** [comment]
This looks like some visualization issue. This is what it should give
<img width="588" alt="image" src="https://github.com/user-attachments/assets/61b367fa-87cd-4d86-a8fc-f5ec9c5d1d60">

**Comment by Amael** [comment]
This is a visualization issue of the depth range. Can you rebase on main (I made visualization update 2 days ago, in https://github.com/apple/ml-depth-pro/commit/b2cd0d51daa95e49277a9f642f7fd736b7f9e91d) and check? The depth output per se is still the same
