### ISSUE TITLE
Black and white (grayscale) depth map

### ISSUE THREAD

**Issue by ajavamind** [apple/ml-depth-pro#23]
I got this working on my Ubuntu computer with a Nvidia RTX 3060.
The example image created a color depth map in 2.5 seconds. Very fast for my system (IMHO).
I need a grayscale depth map for my stereo photo maker tool to convert the example into a 3D image for evaluation.
How can I get a black/white (grayscale) depth map instead of color?

**Comment by 99991** [comment]
If you are using the command line helper script, you will get a grayscale depth map if you change the color map from `"turbo"` to `"gray"` in `src/depth_pro/cli/run.py`: https://github.com/apple/ml-depth-pro/blob/b2cd0d51daa95e49277a9f642f7fd736b7f9e91d/src/depth_pro/cli/run.py#L98

The line should be:

```python
            cmap = plt.get_cmap("gray") 
```

If you then run the script like so:

```bash
depth-pro-run -i my_image.jpg --output-path my_output
```

You will get a new directory with the name `my_output` and the file `my_output/my_image.jpg` in grayscale.

**Comment by ajavamind** [comment]
Thanks, that worked.
