### ISSUE TITLE
8x faster inference using tensorrt

### ISSUE THREAD

**Issue by yuvraj108c** [apple/ml-depth-pro#25]
https://github.com/yuvraj108c/ml-depth-pro-tensorrt

**Comment by Amael** [comment]
Title is misleading. Numbers reported in the paper are on a V100, yours are on a H100.

**Comment by yuvraj108c** [comment]
@Amael I did not take benchmarks from the paper. I did my own benchmarks with the pytorch implementation and tensorrt implementation. (525ms vs 1.8ms)

**Comment by nagadomi** [comment]
@yuvraj108c 
Your benchmark code is missing CUDA stream synchronization.
After fixing that it takes about 300ms on my env. It is 1.7x faster than pytorch impl a reasonable improvement.
```python
s = time.time()
stream = cuda.Stream()
prediction= engine.infer({"input": image_t}, stream, use_cuda_graph=False) 
stream.synchronize()                                                           
e = time.time()
```

**Comment by yuvraj108c** [comment]
ok, I did not know about that @nagadomi 

The 1st benchmark (60ms, 8x faster) was using cuda_graph, no synchronization
When I disabled cuda graphs, I was getting 2 ms

Now, I added the cuda stream synchronization
i still get around 60ms on h100, compared to 500ms pytorch (forward function only)
but there are noticeable loss of quality of the depth result
