### ISSUE TITLE
depth-pro-run: command not found

### ISSUE THREAD

**Issue by xyh1233** [apple/ml-depth-pro#26]
:~/ml-depth-pro-main/ml-depth-pro-main$ depth-pro-run -i ./data/example.jpg
depth-pro-run: command not found
How to solve it?

**Comment by 99991** [comment]
Did you install Depth Pro as described in the [Getting Started section](https://github.com/apple/ml-depth-pro?tab=readme-ov-file#getting-started)?

In my case, the file appeared in the directory `~/miniconda3/envs/depth-pro/bin/depth-pro-run`. Search for the file and see if you can run it.

Alternatively, you could download [`run.py`](https://raw.githubusercontent.com/apple/ml-depth-pro/refs/heads/main/src/depth_pro/cli/run.py) and execute that instead:

```bash
python run.py -i data/example.jpg
```

**Comment by nok** [comment]
Here is another approach. You could force the use of the right environment:

```bash
conda run -n depth-pro depth-pro-run -i ./data/example.jpg
```

**Comment by xyh1233** [comment]
> 您是否按照 [入门 部分](https://github.com/apple/ml-depth-pro?tab=readme-ov-file#getting-started)的说明安装了 Depth Pro？
> 
> 就我而言，该文件出现在目录中。搜索该文件，看看是否可以运行它。`~/miniconda3/envs/depth-pro/bin/depth-pro-run`
> 
> 或者，您可以下载[](https://raw.githubusercontent.com/apple/ml-depth-pro/refs/heads/main/src/depth_pro/cli/run.py)并执行该操作：
> 
> ```shell
> python run.py -i data/example.jpg
> ```

I did conda create -n depth-pro -y python=3.9
conda activate depth-pro
pip install -e .
But the file did not appeare in the directory '~/anaconda3/envs/depth-pro/bin'

**Comment by 99991** [comment]
> > 您是否按照 [入门 部分](https://github.com/apple/ml-depth-pro?tab=readme-ov-file#getting-started)的说明安装了 Depth Pro？
> > 就我而言，该文件出现在目录中。搜索该文件，看看是否可以运行它。`~/miniconda3/envs/depth-pro/bin/depth-pro-run`
> > 或者，您可以下载并执行该操作：
> > ```shell
> > python run.py -i data/example.jpg
> > ```
> 
> I did conda create -n depth-pro -y python=3.9 conda activate depth-pro pip install -e . But the file did not appeare in the directory '~/anaconda3/envs/depth-pro/bin'

That is strange. Does the file appear anywhere else?

You can search with the command

```bash
find / -name depth-pro-run 2>&1 | grep -v 'Permission denied'
```

The directory containing the file `depth-pro-run` should be listed in your `PATH` environment variable so your operating system can run it. You can list the directories with

```bash
echo $PATH
```

Also, it looks like your translation software removed the link to download `run.py` in my comment earlier, so here it is again:

https://raw.githubusercontent.com/apple/ml-depth-pro/refs/heads/main/src/depth_pro/cli/run.py

Maybe it works if you download it and run it directly, although it would be interesting to find out why it did not work before.

**Comment by xyh1233** [comment]
> > > 您是否按照 [入门 部分](https://github.com/apple/ml-depth-pro?tab=readme-ov-file#getting-started)的说明安装了 Depth Pro？
> > > 就我而言，该文件出现在目录中。搜索该文件，看看是否可以运行它。
> > > 或者，您可以下载并执行该操作：`~/miniconda3/envs/depth-pro/bin/depth-pro-run`
> > > ```shell
> > > python run.py -i data/example.jpg
> > > ```
> > 
> > 
> > I did conda create -n depth-pro -y python=3.9 conda activate depth-pro pip install -e . But the file did not appeare in the directory '~/anaconda3/envs/depth-pro/bin'
> 
> That is strange. Does the file appear anywhere else?
> 
> You can search with the command
> 
> ```shell
> find / -name depth-pro-run 2>&1 | grep -v 'Permission denied'
> ```
> 
> The directory containing the file should be listed in your environment variable so your operating system can run it. You can list the directories with`depth-pro-run``PATH`
> 
> ```shell
> echo $PATH
> ```
> 
> Also, it looks like your translation software removed the link to download in my comment earlier, so here it is again:`run.py`
> 
> https://raw.githubusercontent.com/apple/ml-depth-pro/refs/heads/main/src/depth_pro/cli/run.py
> 
> Maybe it works if you download it and run it directly, although it would be interesting to find out why it did not work before.

**Comment by xyh1233** [comment]
Thank you for your generous help.
