### ISSUE TITLE
Long inference time

### ISSUE THREAD

**Issue by SuteraBlu** [apple/ml-depth-pro#41]
My GPU is RTX 4090, but the inference time on 1 single image could reach 18 seconds.
Is it normal?

**Comment by lattebyte** [comment]
Mine is RTX3090, it took approx a few hundred milliseconds for inference per image frame (not much difference w/o resize), the 18s sounds like CPU computing time. maybe have a try with steps below to enable GPU.

https://github.com/lattebyte/DepthPro-Windows-GPU

**Comment by bharath5673** [comment]
#tested on colab// this were the results on './data/example.jpg'

Using GPU: Tesla T4
Memory Allocated: 3.82 GB
Memory Cached: 11.46 GB
Inference Time: 3.40 sec
