### ISSUE TITLE
Wrong depth results ？

### ISSUE THREAD

**Issue by juntaosun** [apple/ml-depth-pro#8]
After testing on different images, I found that many depth results are wrong? 
Are there plans to release medium/small models in the future?

![err1](https://github.com/user-attachments/assets/11094b36-402d-4eaa-b2ec-4024ec612812)

![err2](https://github.com/user-attachments/assets/37820897-c72e-4317-9349-5df941345d75)

![err3](https://github.com/user-attachments/assets/9ead2dd2-be3e-497f-8405-58e2e626fadc)

**Comment by srrichter** [comment]
The problem here is probably just the visualization of the large depth range in the image. If you display inverse depth (1.0/depth) instead of depth, it should look much better on this kind of image.

**Comment by zhouzhubin** [comment]
@juntaosun 您好，请问您是怎么解决的，我在墙的60cm拍摄，模型给出来的depth 差不多有90cm

**Comment by jeezrick** [comment]
> @juntaosun 您好，请问您是怎么解决的，我在墙的60cm拍摄，模型给出来的depth 差不多有90cm

这个问题应该解决不了。模型就是这样的效果。从原理上来说光从图片预测距离是很难做到的，这个模型更擅长的是给出一个合理的，并且平滑的深度。从论文里看，还擅长边缘的处理。

**Comment by zhouzhubin** [comment]
> > @juntaosun 您好，请问您是怎么解决的，我在墙的60cm拍摄，模型给出来的depth 差不多有90cm
> 
> 这个问题应该解决不了。模型就是这样的效果。从原理上来说光从图片预测距离是很难做到的，这个模型更擅长的是给出一个合理的，并且平滑的深度。从论文里看，还擅长边缘的处理。

恩恩，好的，谢谢
