### ISSUE TITLE
progress bar stuck at 0%

### ISSUE THREAD

**Issue by flurrux** [apple/ml-depth-pro#9]
when i run the model on the example image, as stated in the readme, i'm getting
`torch.load("checkpoints/depth_pro.pt", map_location="cpu")`
and underneath a progress bar that's stuck at 0%.

![Screenshot 2024-10-05 190249](https://github.com/user-attachments/assets/dc00d56d-f75e-4ae3-8508-fef3f3843443)

task manager shows that the python script is running, but i cancelled the process after 20 minutes since no progress was visible.
is something wrong with the script or do i have  to wait longer?

my specs:
i have an AMD Ryzen 5 5500U processor with 16GB of RAM.

**Comment by srrichter** [comment]
The script opens a window with the result displayed. The script waits until you close the window before proceeding with the next image.

**Comment by flurrux** [comment]
i see the window, but it is blank and when hovered, shows a loading indicator.
![Screenshot 2024-10-05 200440](https://github.com/user-attachments/assets/8d767252-6f72-4be6-a8b8-95664488681b)

**Comment by you-knowww** [comment]
@flurrux been having the same issue. Same issue when i add -o and --skip-display flags too. Have you figured out what was wrong in your case?

**Comment by flurrux** [comment]
@you-knowww i wasn't able to fix it locally, but i found this online version:
https://huggingface.co/spaces/akhaliq/depth-pro
which is good enough for me.

**Comment by gfugante** [comment]
> I encountered the same issue when running on CPU in a Colab notebook without GPU acceleration. The workaround mentioned in issue #9 resolved the problem for me.
> 
> Specifically, running the command with the -`-skip-display` flags allowed it to execute successfully, this works for me:
> ```
> depth-pro-run -i ./data/example.jpg -o ./data/example_output.jpg --skip-display
> ```
> Note that the progress percentage bar remained stuck at 0% throughout execution. On CPU, the process took approximately 1 hour and 30 minutes, but it eventually completed and produced the correct output.
> 
> ### System Information
> ```
> Environment: Google Colab (Free Tier)
> CPU: Intel Xeon @ 2.20GHz 
> RAM: 12.7 GB
> GPU: GPU runtime disabled
> OS: Ubuntu 22.4
> Python Version: 3.10
> ```
>  

 _Originally posted by @gfugante in [#76](https://github.com/apple/ml-depth-pro/issues/76#issuecomment-2832442538)_
